### ISSUE TITLE
채팅화면 내 이용약관 URL 연결 처리

### ISSUE THREAD

**Issue by dev-summer** [Team-TravelGenie/TripChat#58]
attributedString 내에 URL 링크 처리
- [ ] OpenAI
- [ ] GoogleVision
- [ ] GoogleCustomSearch
- [ ] Papago Translate

**Comment by dev-summer** [comment]
OpenAI 운영방침/정책 https://openai.com/policies

**Comment by dev-summer** [comment]
GoogleCustomSearch - 별도 약관 없음 (과금 관련 서비스 정책만 존재) → 본문에 적지 않아도 될 듯

**Comment by iOS-Woong** [comment]
NAVER Developers 운영 정책: 
https://developers.naver.com/products/intro/operation/operation.md#naver-developers-%EC%9A%B4%EC%98%81-%EC%A0%95%EC%B1%85
